server:
  port: 8989

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 文件上传配置
  servlet:
    multipart:
      # HTTP请求中包含的所有文件的总大小的最大允许值
      max-request-size: 100MB
      # 单个上传文件的最大允许大小
      max-file-size: 20MB

  data:
      redis:
        host: 127.0.0.1
        port: 6379



mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml  # 扫描所有模块的 XML 文件
  configuration:
    # 日志
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰命名映射
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 逻辑删除的字段
      logic-delete-field: delFlag
      # 代表已删除的值
      logic-delete-value: 1
      # 代表未删除的值
      logic-not-delete-value: 0
      id-type: AUTO

springdoc:
  api-docs:
    enabled: true
    path: /blog/v3/api-docs
  swagger-ui:
    enabled: true
    path: /blog/swagger-ui/index.html



aliyun:
    oss:
      endpoint: https://oss-cn-beijing.aliyuncs.com
      bucketName: test-for-tree
      region: cn-beijing